FROM maven:3.5-jdk-10-slim

MAINTAINER D.Valocchi <d.valocchi@ucl.ac.uk>

ADD adaptor /adaptor

WORKDIR /adaptor

RUN mvn -e -q compile assembly:single;
#RUN mvn -Dmaven.wagon.http.ssl.insecure=true -Dmaven.wagon.http.ssl.allowall=true -Dmaven.wagon.http.ssl.ignore.validity.dates=true clean compile assembly:single;

RUN apt-get update && apt-get install --no-install-recommends -y \
   netcat && rm -rf /var/lib/apt/lists/*

ADD broker.config /etc/son-mano/broker.config
ADD postgres.config /etc/son-mano/postgres.config
ADD sonata.config /etc/son-mano/sonata.config

ADD son-sp-infra-* /usr/local/bin/
ADD son-sp-infra /etc/init.d/
ADD ./setenv.sh \
   ./test.sh \
   ./docker-entrypoint.sh /

RUN chmod +x /setenv.sh \
   /test.sh \
   /docker-entrypoint.sh \
   /usr/local/bin/son-sp-infra-* \
   /etc/init.d/son-sp-infra

ENV broker_host broker
ENV broker_port 5672
ENV broker_exchange son-kernel
ENV broker_uri amqp://guest:guest@broker:5672/%2F

ENV repo_host postgres
ENV repo_port 5432
ENV repo_user sonatatest
ENV repo_pass sonata
ENV SONATA_SP_ADDRESS 127.0.0.1


CMD ["/docker-entrypoint.sh","/test.sh"]


